/**
 * Hand-written helper types mirrored 1:1 from `hunter_core.domain.enums`
 * (packages/core/hunter_core/domain/enums.py) and from the RFC 9457
 * problem+json shape every `apps/api` error uses (apps/api/hunter_api/errors.py).
 *
 * The OpenAPI document already carries these as inline string enums on each
 * schema that uses them (see `./api`, generated by `pnpm gen:types`), but a
 * bare union pulled out of `paths`/`components` by consumers would depend on
 * exactly which endpoint happened to reference it. These are named, top-level
 * types precisely so both `apps/web` and any future consumer can import one
 * shared name instead of re-deriving it per call site — the same rationale
 * CLAUDE.md gives for "enums mirrored 1:1 between Postgres, Pydantic and TS".
 *
 * Keep in sync with `packages/core/hunter_core/domain/enums.py` by hand; only
 * the enums M0 actually surfaces through the API are listed here, not the
 * whole module (`ALL_ENUMS` there covers concepts that don't exist as
 * frontend-facing types until their milestone lands).
 */

/** `org_role` — hunter_core.domain.enums.OrganizationRole. */
export type Role = "OWNER" | "ADMIN" | "TRADER" | "ANALYST" | "VIEWER";

/** `plan_tier` — hunter_core.domain.enums.Plan. */
export type Plan = "FREE" | "PRO" | "QUANT" | "ENTERPRISE";

/** `kill_switch_state` — hunter_core.domain.enums.KillSwitchState. */
export type KillSwitchState = "ACTIVE" | "WARNING" | "TRADING_DISABLED" | "EMERGENCY";

/** `member_status` — hunter_core.domain.enums.MemberStatus. */
export type MemberStatus = "invited" | "active" | "suspended";

/** `workspace_objective` — hunter_core.domain.enums.WorkspaceObjective. */
export type OnboardingObjective = "explore" | "paper_trading" | "research" | "automated_trading";

/** `risk_preset` — hunter_core.domain.enums.RiskPreset. */
export type RiskPreset = "conservative" | "balanced" | "aggressive" | "custom";

/**
 * RFC 9457 `application/problem+json` (apps/api/hunter_api/errors.py). Every
 * non-2xx response from `apps/api` has at least these fields; `errors` is
 * present on 422 validation failures (`_sanitize_validation_errors`), and
 * `request_id` is present whenever `RequestIdMiddleware` ran (always, outside
 * a handler crashing before it).
 */
export interface Problem {
  type: string;
  title: string;
  status: number;
  // `| undefined` alongside the optional `?` on purpose: consumers compile
  // with `exactOptionalPropertyTypes` (packages/config/tsconfig.base.json),
  // under which `field?: T` and `field?: T | undefined` are different types
  // -- only the latter accepts an explicitly-`undefined` value (e.g. from
  // `ApiError.detail`), not just an absent key.
  detail?: string | null | undefined;
  instance?: string | undefined;
  request_id?: string | undefined;
  errors?: Array<{ loc: (string | number)[]; msg: string; type: string }> | undefined;
  [key: string]: unknown;
}
