/** Shared fixtures for the test-record suite (T4.13) -- shaped exactly like `TestsListOut`/`TestRowOut` of the generated types; every number a decimal string. */
import type { MemeTestRow, MemeTests } from "@/lib/api/meme-tests-types";

export const ENTRY_AT = "2026-09-12T14:00:05Z"; // 11:00:05 Brasília
export const EXIT_AT = "2026-09-12T14:07:30Z"; // 11:07:30 Brasília

export function testRow(overrides: Partial<MemeTestRow> = {}): MemeTestRow {
  return {
    id: "bet-1",
    kind: "paper",
    kind_label: "PAPEL — aposta simulada do laço",
    bet_id: "bet-1",
    proposal_id: "prop-1",
    mint: "Fh42kAfy27CGoUA8CgFwpTGMubzndaAyTy2gghu5pump",
    token_name: "bum bum",
    token_symbol: "BAM",
    status: "closed",
    rule_set: { name: "meme_paper_v0", version: "1", kind: "research_only", label: "meme_paper_v0/1" },
    leg: "single",
    parent_bet_id: null,
    origin: "rules",
    decided_by: "rules",
    entry: {
      at: ENTRY_AT,
      price_sol_per_token: "0.00000003",
      average_price_sol: "0.0000000305",
      mcap_sol: "31.5",
      sol_spent: "0.2",
      tokens: "6443000",
      fee_sol: "0.0035",
      fee_pct: "1.75",
      fill_delay_s: 40,
      fill_delay_snapshots: 1,
      source: "solana_rpc",
    },
    exit: {
      at: EXIT_AT,
      provisional: false,
      price_sol_per_token: "0.000000058",
      mcap_sol: "60.1",
      sol_received: "0.38",
      fee_sol: "0.0066",
      reason: "target",
      reason_label: "alvo atingido",
      trigger: "rules",
      pending_reason: null,
    },
    duration_s: 445,
    pnl_sol: "0.18",
    pnl_usd: "32.58",
    pnl_usd_basis: "exit_quote",
    pnl_usd_reason: null,
    r_multiple: "0.9",
    outcome_quality: "measured",
    outcome_quality_label: "medido",
    outcome_quality_reason: null,
    sol_usd_at_entry: "179",
    sol_usd_at_exit: "181",
    sol_usd_source: "coingecko",
    lab_context: {
      features_end_time: "2026-09-12T13:59:00Z",
      features_version: "meme_features_v3",
      reason: null,
      gate_reasons: ["progress_gate", "age_gate"],
      line_drawn: true,
      line_reason: null,
      support_line_sol: "28.4",
      distance_to_support_pct: "0.11",
      higher_lows: true,
      breakout_15m: true,
      hype_score: "0.7",
      hype_reason: "partial",
      creator_sold: false,
      creator_sold_reason: null,
      curve_progress_pct: "0.42",
      progress_reason: null,
      age_minutes: 8,
      unique_buyers: 12,
      mcap_sol: "31.2",
    },
    wallet: null,
    mark_source: null,
    ...overrides,
  };
}

export function realRow(overrides: Partial<MemeTestRow> = {}): MemeTestRow {
  return testRow({
    id: "6nAh8drzAYfFZuTFFRgwRdV8tNndFiX1E8NGRAGzSk5F:mint",
    kind: "real_observed",
    kind_label: "REAL — observado na cadeia, não executado por este sistema",
    bet_id: null,
    proposal_id: null,
    token_name: "moeda real",
    rule_set: { name: "wallet:6nAh8drz", version: null, kind: "real_observed", label: "wallet:6nAh8drz" },
    origin: "wallet",
    decided_by: null,
    entry: { ...testRow().entry, at: "2026-09-12T14:03:00Z", price_sol_per_token: null, average_price_sol: null, mcap_sol: null, fee_sol: null, fee_pct: null, fill_delay_s: null, fill_delay_snapshots: null, source: "chain" },
    exit: { ...testRow().exit, at: "2026-09-12T14:13:00Z", price_sol_per_token: null, mcap_sol: null, fee_sol: null, sol_received: "0.7", reason: null, reason_label: "saída sem motivo registrado", trigger: "wallet" },
    duration_s: 600,
    pnl_sol: "0.2",
    pnl_usd: null,
    pnl_usd_basis: null,
    pnl_usd_reason: "no_exit_quote",
    r_multiple: "0.4",
    sol_usd_at_entry: null,
    sol_usd_at_exit: null,
    sol_usd_source: null,
    wallet: "6nAh8drzAYfFZuTFFRgwRdV8tNndFiX1E8NGRAGzSk5F",
    mark_source: "swap_api",
    ...overrides,
  });
}

export function testsPayload(overrides: Partial<MemeTests> = {}): MemeTests {
  return {
    label: "Registro de testes — papel e REAL observado lado a lado; nada aqui executa",
    server_now: "2026-09-12T15:00:00Z",
    day: "2026-09-12",
    day_start: "2026-09-12T03:00:00Z",
    day_end: "2026-09-13T03:00:00Z",
    rule_set: null,
    rule_sets: ["meme_paper_v0", "operator"],
    totals: { bets: 3, closed: 2, open: 1, wins: 2, losses: 0, indeterminate: 0, pnl_sol: "0.36", provisional_pnl_sol: "0.05", pnl_usd: "65.16", unpriced_usd: 0, r_sum: "1.8", real_rows: 0 },
    sources: { wallets: "não observada", features_version: "meme_features_v3" },
    items: [testRow()],
    real_items: [],
    next_cursor: null,
    ...overrides,
  };
}
