"""``0066_meme_mature_opportunities`` — the durable record of EXP-M26's first
opportunity per (rule set, mint) (R1, ``docs/design/exp-m26-grafico-moedas-maduras.md``
§1.6/§2.2/§7, H-022).

**Why it exists.** H-022's primary contrast is read on the **first** minute a
coin passes the pure gate of ``grafico_ctrl_v1/1``, with the inputs the 1-minute
lane read at that tick. Nothing else keeps that: the lane writes proposals and
per-tick counters (``meme_lab_ticks``), never the individual evaluation; the
refusal trail is sampled (0 or 1 refusal) and pruned in 7 d; Mayhem is read from
``meme_tokens``' current state; ``completed_at``/``migrated_at`` are tested by
presence. A later reconstruction would call a ``creator_serial`` exclusion
"no proposal by instrument", or drop a valid opportunity because the token has
since migrated (design §1.6, R1).

**One row per (EXP-M26 rule set, mint)**, written once by the 1-minute lab lane
(``hunter_meme_worker.lab_opportunities``) on the first evaluation where the
set's pure gate lets the mint through: the tick (``evaluated_at``, the one
clock), the minute and the version of the features it judged, the commit, the
inputs as read (typed columns for what H-022 classifies on, the whole row in
``inputs``), the pure gate's decomposition, the pedigree as read, the coverage
guard's version, parameters and result, **every** refusal of the proposal layer
by name, and the proposal it produced or the named reason it did not.

Global (no ``organization_id``), no RLS (§1.1), like ``meme_decision_tapes``:
the row describes a public coin judged by a research rule set, it belongs to
the Lab, not to an organisation. Append-only by privilege: ``hunter_worker``
gets ``SELECT``/``INSERT`` — **no** ``UPDATE`` (a first opportunity is never
rewritten) and **no** ``DELETE`` (no retention until H-022 is read: ~300 rows
per day per set, design §1.6); ``hunter_app`` gets ``SELECT``. The id is a
UUID v7 generated by the worker (§1), no server default.
"""

from __future__ import annotations

from alembic import op

from hunter_core.db.models import APP_ROLE, WORKER_ROLE

TABLE = "meme_mature_opportunities"

NO_PROPOSAL_REASONS: tuple[str, ...] = ("refused", "insert_failed", "not_inserted")
"""``refused`` — the proposal layer refused (the names are in
``proposal_refusals``); ``insert_failed`` — the proposal's own ``INSERT`` failed
and was rolled back to its savepoint; ``not_inserted`` — the ``INSERT`` hit the
idempotence key and no existing proposal could be found to link."""

FIDELITIES: tuple[str, ...] = (
    "faithful",
    "earlier_pass_unrecorded",
    "write_failed",
    "eligible_before_lane",
)
"""Whether the row can be read as the first opportunity: ``faithful``; or an
instrument failure that must never be read as a substitute —
``earlier_pass_unrecorded`` (an earlier pass of the same set on the same mint
left a proposal, or failed to write in this process, and no row), or
``write_failed`` (the full row failed to insert; this minimal row, written in
its own savepoint, is the durable marker that blocks a later substitute), or
``eligible_before_lane`` (the mint could pass the gate in a minute before the
first one the writing process evaluated: a restart gap may hide its first pass)."""

COVERAGE_STATUSES: tuple[str, ...] = ("covered", "covered_from_birth", "gap", "unread")
"""The coverage guard of design §1.6 at the tick: the union window
``(T − 16 min, T]`` fully observed (``covered``), observed from the coin's
creation when it is younger than 16 min (``covered_from_birth``, the window is
truncated at birth), not observed (``gap``), or the photos could not be read
(``unread``)."""


def _labels(values: tuple[str, ...]) -> str:
    return ", ".join(f"'{value}'" for value in values)


_CREATE = f"""
CREATE TABLE {TABLE} (
    id uuid NOT NULL,
    rule_set_id uuid NOT NULL,
    mint text NOT NULL,
    evaluated_at timestamptz NOT NULL,
    features_end_time timestamptz NOT NULL,
    features_version text NOT NULL,
    features_computed_at timestamptz,
    code_ref text NOT NULL,
    age_s integer,
    curve_progress_pct numeric(9, 6),
    mcap_sol numeric(28, 10),
    curve_volume_1m_sol numeric(28, 10),
    participation_pct numeric(28, 10),
    creator_net_seller boolean,
    higher_lows boolean,
    breakout_15m boolean,
    distance_to_support_pct numeric(9, 6),
    line_reason text,
    line_points smallint,
    mcap_slope_15m numeric(12, 6),
    mayhem_enabled boolean,
    mayhem_state text,
    completed_at timestamptz,
    migrated_at timestamptz,
    inputs jsonb NOT NULL,
    gate jsonb NOT NULL,
    pedigree jsonb,
    coverage_version text NOT NULL,
    coverage_status text NOT NULL,
    coverage jsonb NOT NULL,
    proposal_refusals text[] NOT NULL DEFAULT '{{}}'::text[],
    proposal_id uuid,
    no_proposal_reason text,
    fidelity text NOT NULL DEFAULT 'faithful',
    lane_since timestamptz NOT NULL,
    recorded_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_{TABLE} PRIMARY KEY (id),
    CONSTRAINT uq_{TABLE}_rule_set_id UNIQUE (rule_set_id, mint),
    CONSTRAINT fk_{TABLE}_rule_set_id_meme_rule_sets
        FOREIGN KEY (rule_set_id) REFERENCES meme_rule_sets (id),
    CONSTRAINT fk_{TABLE}_proposal_id_meme_proposals
        FOREIGN KEY (proposal_id) REFERENCES meme_proposals (id),
    CONSTRAINT ck_{TABLE}_mint_not_blank CHECK (mint <> ''),
    CONSTRAINT ck_{TABLE}_features_version_not_blank CHECK (features_version <> ''),
    CONSTRAINT ck_{TABLE}_code_ref_not_blank CHECK (code_ref <> ''),
    CONSTRAINT ck_{TABLE}_coverage_version_not_blank CHECK (coverage_version <> ''),
    CONSTRAINT ck_{TABLE}_the_minute_closed_before_the_tick
        CHECK (features_end_time <= evaluated_at),
    CONSTRAINT ck_{TABLE}_the_lane_ran_before_the_minute
        CHECK (lane_since <= features_end_time),
    CONSTRAINT ck_{TABLE}_fidelity_is_a_known_label
        CHECK (fidelity IN ({_labels(FIDELITIES)})),
    CONSTRAINT ck_{TABLE}_age_is_not_negative CHECK (age_s IS NULL OR age_s >= 0),
    CONSTRAINT ck_{TABLE}_line_points_are_not_negative
        CHECK (line_points IS NULL OR line_points >= 0),
    CONSTRAINT ck_{TABLE}_inputs_is_an_object CHECK (jsonb_typeof(inputs) = 'object'),
    CONSTRAINT ck_{TABLE}_gate_is_an_array CHECK (jsonb_typeof(gate) = 'array'),
    CONSTRAINT ck_{TABLE}_pedigree_is_an_object
        CHECK (pedigree IS NULL OR jsonb_typeof(pedigree) = 'object'),
    CONSTRAINT ck_{TABLE}_coverage_is_an_object CHECK (jsonb_typeof(coverage) = 'object'),
    CONSTRAINT ck_{TABLE}_coverage_status_is_a_known_label
        CHECK (coverage_status IN ({_labels(COVERAGE_STATUSES)})),
    CONSTRAINT ck_{TABLE}_no_proposal_reason_is_known
        CHECK (no_proposal_reason IS NULL
               OR no_proposal_reason IN ({_labels(NO_PROPOSAL_REASONS)})),
    CONSTRAINT ck_{TABLE}_a_proposal_or_a_reason
        CHECK ((proposal_id IS NULL) <> (no_proposal_reason IS NULL)),
    CONSTRAINT ck_{TABLE}_refused_iff_refusals_are_named
        CHECK ((no_proposal_reason IS NOT DISTINCT FROM 'refused')
               = (cardinality(proposal_refusals) > 0))
)
"""
_INDEXES: tuple[str, ...] = (
    f"CREATE INDEX ix_{TABLE}_rule_set_evaluated_at ON {TABLE} (rule_set_id, evaluated_at)",
    f"CREATE INDEX ix_{TABLE}_proposal_id ON {TABLE} (proposal_id) WHERE proposal_id IS NOT NULL",
)
"""The research read is "every opportunity of set S with ``evaluated_at`` in
[T0, cut)" (design §4); ``(rule_set_id, mint)`` already serves the per-mint read
and the ``rule_set_id`` foreign key. The partial index serves the
``proposal_id`` foreign key (every FK indexed, §1) and the join to the bet."""

MEME_MATURE_OPPORTUNITIES_APP_READ_ONLY_TABLES: tuple[str, ...] = (TABLE,)
MEME_MATURE_OPPORTUNITIES_WORKER_APPEND_TABLES: tuple[str, ...] = (TABLE,)


def create_meme_mature_opportunities() -> None:
    op.execute(_CREATE)
    for statement in _INDEXES:
        op.execute(statement)


def grant_meme_mature_opportunities_privileges() -> None:
    for table in MEME_MATURE_OPPORTUNITIES_APP_READ_ONLY_TABLES:
        op.execute(f"GRANT SELECT ON {table} TO {APP_ROLE}")
    for table in MEME_MATURE_OPPORTUNITIES_WORKER_APPEND_TABLES:
        op.execute(f"GRANT SELECT, INSERT ON {table} TO {WORKER_ROLE}")


def drop_meme_mature_opportunities() -> None:
    op.execute(f"DROP TABLE IF EXISTS {TABLE}")


def refuse_a_downgrade_that_would_lose_an_opportunity() -> None:
    """§17.7: reversing is allowed, losing H-022's population is not. The lock
    comes first (``0062``'s order): counting and then dropping leaves a window
    for the lab lane to insert a row between the two."""
    op.execute(f"LOCK TABLE {TABLE} IN ACCESS EXCLUSIVE MODE")
    op.execute(
        f"DO $$ DECLARE offenders bigint; BEGIN "  # noqa: S608 - this module's own frozen table name
        f"SELECT count(*) INTO offenders FROM {TABLE}; "
        f"IF offenders > 0 THEN RAISE EXCEPTION USING "
        f"MESSAGE = 'PROJECT HUNTER: ' || offenders || ' {TABLE} rows exist - "
        f"the first opportunity per mint of EXP-M26 (H-022); nothing else can rebuild it', "
        f"HINT = 'COPY (SELECT * FROM {TABLE}) TO ... before reversing'; "
        f"END IF; END $$;"
    )
