"""shadow lab: frozen strategy versions, tracking state, episodes and outbox

The durable half of docs/plans/SHADOW-LAB.md (task S0). Nothing here is a
feature; all of it is what has to be true *before* the first strategy version is
activated, because a shadow experiment whose parameters, tracking state or
event delivery can drift afterwards produces numbers nobody may believe.

Four things, in the order Postgres accepts them:

1. the ``shadow_tracking_state`` enum (``ddl/enums.py`` owns every ``CREATE
   TYPE``; this revision's tuple is ``SHADOW_ENUMS``);
2. the columns and tables — ``signal_outcomes.tracking_state``/``meta`` and the
   two reason columns, ``strategy_versions.params_format``, ``shadow_episodes``
   and ``shadow_outbox`` — plus the CHECKs that keep the three axes of an
   outcome coherent (``SignalStatus``, ``OutcomeResult``, ``tracking_state``);
3. grants: ``SELECT`` for ``hunter_app``, full DML for ``hunter_worker``, and
   ``USAGE`` on ``shadow_outbox``'s sequence — the first sequence in the schema;
4. the freeze trigger on ``strategy_versions``: after the first activation,
   ``strategy_id``, ``version``, ``code_ref``, ``parameters_schema``,
   ``default_parameters``, ``params_format`` and ``activated_at`` (including
   ``SET NULL``) can no longer change, in any status, and the row cannot be
   deleted. ``status``, ``changelog`` and ``deprecated_at`` stay mutable.

``downgrade()`` reverses all four and is tested (``test_migrations.py``).

This is the ``0002`` the M2 plan's T2.1 said it would write: T2.1 now *depends*
on this revision instead of recreating its objects, and lands as ``0003``.

Revision ID: 0002_shadow_lab
Revises: 0001_initial_schema
Create Date: 2026-09-05
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from ddl.enums import SHADOW_ENUMS, create_enum_types, drop_enum_types
from ddl.shadow import (
    create_strategy_version_freeze,
    drop_strategy_version_freeze,
    grant_shadow_privileges,
    revoke_shadow_privileges,
)
from sqlalchemy.dialects import postgresql

revision: str = "0002_shadow_lab"
down_revision: str | None = "0001_initial_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    create_enum_types(SHADOW_ENUMS)
    _create_tables()
    grant_shadow_privileges()
    create_strategy_version_freeze()


def downgrade() -> None:
    drop_strategy_version_freeze()
    revoke_shadow_privileges()
    _drop_tables()
    drop_enum_types(SHADOW_ENUMS)


def _create_tables() -> None:
    """Autogenerated from hunter_core.db.models, with two hand-placed steps.

    The unique constraint on ``agent_signals`` comes **first**: it is the target
    of ``shadow_episodes``' composite foreign key, and autogenerate emitted it
    after the table that references it. The ``UPDATE`` that backfills
    ``tracking_state`` comes before the CHECK that constrains it, for the reason
    written where it stands.
    """
    op.create_unique_constraint(
        "uq_agent_signals_id_slot", "agent_signals", ["id", "strategy_version_id", "market_id"]
    )
    op.create_table(
        "shadow_outbox",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("stream", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("dispatched_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_shadow_outbox_attempts_not_negative")),
        sa.CheckConstraint(
            "char_length(stream) > 0", name=op.f("ck_shadow_outbox_stream_not_empty")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shadow_outbox")),
        sa.UniqueConstraint("event_id", name=op.f("uq_shadow_outbox_event_id")),
    )
    op.create_index(
        "ix_shadow_outbox_pending",
        "shadow_outbox",
        ["id"],
        unique=False,
        postgresql_where=sa.text("dispatched_at IS NULL"),
    )
    op.create_table(
        "shadow_episodes",
        sa.Column("strategy_version_id", sa.UUID(), nullable=False),
        sa.Column("market_id", sa.UUID(), nullable=False),
        sa.Column("cohort", sa.Text(), nullable=False),
        sa.Column("episode_id", sa.UUID(), nullable=False),
        sa.Column("last_bar_close", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("armed", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("open_outcome_signal_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cohort ~ '^(prospective|replay:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}"
            "-[0-9a-f]{4}-[0-9a-f]{12})$'",
            name=op.f("ck_shadow_episodes_cohort_format"),
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
            name=op.f("fk_shadow_episodes_market_id_markets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["open_outcome_signal_id", "strategy_version_id", "market_id"],
            ["agent_signals.id", "agent_signals.strategy_version_id", "agent_signals.market_id"],
            name=op.f("fk_shadow_episodes_open_outcome_signal_id_agent_signals"),
            ondelete="SET NULL (open_outcome_signal_id)",
        ),
        sa.ForeignKeyConstraint(
            ["open_outcome_signal_id"],
            ["signal_outcomes.signal_id"],
            name=op.f("fk_shadow_episodes_open_outcome_signal_id_signal_outcomes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_versions.id"],
            name=op.f("fk_shadow_episodes_strategy_version_id_strategy_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shadow_episodes")),
        sa.UniqueConstraint(
            "strategy_version_id", "market_id", "cohort", name="uq_shadow_episodes_slot"
        ),
    )
    op.create_index(
        "ix_shadow_episodes_hold",
        "shadow_episodes",
        ["market_id"],
        unique=False,
        postgresql_where=sa.text("open_outcome_signal_id IS NOT NULL"),
    )
    op.create_index(
        "uq_shadow_episodes_open_outcome",
        "shadow_episodes",
        ["open_outcome_signal_id"],
        unique=True,
        postgresql_where=sa.text("open_outcome_signal_id IS NOT NULL"),
    )
    op.add_column(
        "signal_outcomes",
        sa.Column(
            "tracking_state",
            postgresql.ENUM(
                "pending_entry",
                "active",
                "terminal",
                "no_entry",
                "censored",
                name="shadow_tracking_state",
                create_type=False,
            ),
            server_default="pending_entry",
            nullable=False,
        ),
    )
    op.add_column("signal_outcomes", sa.Column("no_entry_reason", sa.Text(), nullable=True))
    op.add_column("signal_outcomes", sa.Column("censored_reason", sa.Text(), nullable=True))
    op.add_column(
        "signal_outcomes",
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    # A legacy row that says "still open" *and* carries an exit timestamp
    # contradicts itself, and no ``tracking_state`` is derivable from it: calling
    # it ``pending_entry`` would offer a finished tracking back to the worker as
    # one waiting to enter. The migration refuses to guess and says which rows to
    # fix (Astra's review, round 2). This is a no-op on every consistent database.
    op.execute(
        "DO $$ DECLARE contradictory bigint; BEGIN "
        "SELECT count(*) INTO contradictory FROM signal_outcomes "
        "WHERE result = 'open' AND exit_ts IS NOT NULL; "
        "IF contradictory > 0 THEN RAISE EXCEPTION USING MESSAGE = "
        "'PROJECT HUNTER: ' || contradictory || ' signal_outcomes rows have "
        "result = ''open'' with an exit_ts; 0002_shadow_lab cannot infer a "
        "tracking_state for them', HINT = 'give each of them its real result "
        "(target/stop/expired/invalidated) and re-run the migration'; "
        "END IF; END $$;"
    )
    # Backfill before the CHECK, not after: a database already carrying an
    # outcome with ``result <> 'open'`` would take the column default
    # ``pending_entry``, violate the biconditional and abort the upgrade — the
    # failure mode is "the migration works on an empty database and on nobody
    # else's". The mapping is derived from columns that already exist, so it
    # invents nothing: a resolved result is ``terminal``, an open outcome that
    # has an entry timestamp is ``active``, anything else is still waiting.
    op.execute(
        "UPDATE signal_outcomes SET tracking_state = (CASE "
        "WHEN result <> 'open' THEN 'terminal' "
        "WHEN entry_ts IS NOT NULL THEN 'active' "
        "ELSE 'pending_entry' END)::shadow_tracking_state"
    )
    op.create_check_constraint(
        op.f("ck_signal_outcomes_no_entry_and_censored_reasons"),
        "signal_outcomes",
        "(tracking_state = 'no_entry') = (no_entry_reason IS NOT NULL) "
        "AND (tracking_state = 'censored') = (censored_reason IS NOT NULL) "
        "AND (no_entry_reason IS NULL OR char_length(no_entry_reason) BETWEEN 1 AND 64) "
        "AND (censored_reason IS NULL OR char_length(censored_reason) BETWEEN 1 AND 64)",
    )
    op.create_check_constraint(
        op.f("ck_signal_outcomes_tracking_state_matches_result"),
        "signal_outcomes",
        "(result = 'open') = (tracking_state <> 'terminal')",
    )
    op.add_column(
        "strategy_versions",
        sa.Column("params_format", sa.Integer(), server_default="1", nullable=False),
    )


def _drop_tables() -> None:
    op.drop_column("strategy_versions", "params_format")
    op.drop_constraint(
        op.f("ck_signal_outcomes_tracking_state_matches_result"), "signal_outcomes", type_="check"
    )
    op.drop_constraint(
        op.f("ck_signal_outcomes_no_entry_and_censored_reasons"), "signal_outcomes", type_="check"
    )
    op.drop_column("signal_outcomes", "meta")
    op.drop_column("signal_outcomes", "censored_reason")
    op.drop_column("signal_outcomes", "no_entry_reason")
    op.drop_column("signal_outcomes", "tracking_state")
    op.drop_index(
        "uq_shadow_episodes_open_outcome",
        table_name="shadow_episodes",
        postgresql_where=sa.text("open_outcome_signal_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_shadow_episodes_hold",
        table_name="shadow_episodes",
        postgresql_where=sa.text("open_outcome_signal_id IS NOT NULL"),
    )
    op.drop_table("shadow_episodes")
    op.drop_index(
        "ix_shadow_outbox_pending",
        table_name="shadow_outbox",
        postgresql_where=sa.text("dispatched_at IS NULL"),
    )
    op.drop_table("shadow_outbox")
    op.drop_constraint("uq_agent_signals_id_slot", "agent_signals", type_="unique")
