"""replay_runs: the receipt of a replay slice becomes durable evidence

Thirteenth revision. One table, no column added anywhere else, no trigger, no
enum, no partition. It answers the brief T3.19b wrote instead of a migration
(``.claude/state/brief-T3.19b-db-replay-runs.md``): the replay engine already
produced a ledger row per run and wrote it to ``system_events`` and to a JSONL,
and neither is durable enough to answer "how many simulated decisions has this
version accumulated, over what window, and when?".

- ``system_events`` is pruned at **30 days** (DATABASE.md §1.3) while
  ``docs/plans/REPLICATION.md`` counts 15 and 30 days of results *after* a
  marker: the operational channel outlives the question by less than the
  question takes to answer;
- the JSONL proves a run only if somebody kept the file.

**One row per slice, not per run** (§25.1). The T3.19b proof replayed 31 days in
eleven commands under a single cohort, so the slice is the unit that actually
happens; ``id`` is a fresh UUID v7 and the run lives in ``run_id``, with
``UNIQUE (run_id, window_from, window_to)`` making a repeated slice idempotent.
The alternative — one row per run, accumulated with ``UPDATE`` — was refused for
the reason the grants state: a receipt whose own writer may edit it is not a
receipt.

**Grants: ``SELECT`` for ``hunter_app``, ``SELECT``/``INSERT`` for
``hunter_worker``, and nothing else for either** — no ``UPDATE``, no ``DELETE``,
for the same reason ``audit_logs`` has none (§1.2). Frozen in
``ddl/replay_runs.py``.

**Global, not tenant** (§1.1): replay is research, like ``agent_signals``,
``signal_outcomes`` and ``shadow_episodes``. No ``organization_id``, therefore
no RLS policy — the same shape ``0002`` and ``0003`` shipped for their tables.

**No upgrade guard, and that is an assertion.** The revision creates a table that
did not exist; there is no stored row it can make unrepresentable. **The
downgrade refuses** while any receipt exists (§17.7): the row is the only copy
that outlives 30 days.

**Nothing here depends on session state** — one ``CREATE TABLE``, one index and
two ``GRANT``s. No session prepared statement, no ``LISTEN``/``NOTIFY``, no
session advisory lock. ``CREATE TABLE`` takes no lock on a relation that does not
yet exist, and the two ``GRANT``s lock only the catalogue (the same measurement
``0005`` made, §15.6): this revision opens no maintenance window.

**Named ``0013_replay_runs`` (17 characters)** — ``alembic_version.version_num``
is ``VARCHAR(32)`` (§17.6). Described in ``docs/DATABASE.md`` §25.

Revision ID: 0013_replay_runs
Revises: 0012_replication
Create Date: 2026-09-08
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from ddl.replay_runs import (
    REPLAY_COHORT_PATTERN_0013,
    grant_replay_run_privileges,
    refuse_a_downgrade_that_would_lose_a_receipt,
    revoke_replay_run_privileges,
)
from sqlalchemy.dialects import postgresql

revision: str = "0013_replay_runs"
down_revision: str | None = "0012_replication"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    _create_table()
    grant_replay_run_privileges()


def downgrade() -> None:
    """Refuse first, then unwind in the exact reverse order of ``upgrade``."""
    refuse_a_downgrade_that_would_lose_a_receipt()
    revoke_replay_run_privileges()
    _drop_table()


def _create_table() -> None:
    """Autogenerated from ``hunter_core.db.models.replay_runs``, with one edit.

    The cohort CHECK is written from :data:`REPLAY_COHORT_PATTERN_0013` instead
    of the literal autogenerate rendered, so this revision and the frozen copy in
    ``ddl/replay_runs.py`` are one string — the model reads the *live*
    ``hunter_core.domain.enums.REPLAY_COHORT_PATTERN``, and a test compares all
    three (the same arrangement ``0002``/``0012`` use for the wider grammar).
    """
    op.create_table(
        "replay_runs",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("cohort", sa.Text(), nullable=False),
        sa.Column("strategy_version_id", sa.UUID(), nullable=False),
        sa.Column("window_from", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("window_to", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("markets", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("finished_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("bars_evaluated", sa.Integer(), nullable=False),
        sa.Column("signals", sa.Integer(), nullable=False),
        sa.Column("outcomes_resolved", sa.Integer(), nullable=False),
        sa.Column("outcomes_open", sa.Integer(), nullable=False),
        sa.Column("seconds", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("decision_lag_s", sa.Integer(), nullable=False),
        sa.Column("workers", sa.SmallInteger(), nullable=False),
        sa.Column(
            "evaluations_by_state",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("errors", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "cohort = 'replay:' || run_id::text",
            name=op.f("ck_replay_runs_cohort_names_the_run"),
        ),
        sa.CheckConstraint(
            f"cohort ~ '{REPLAY_COHORT_PATTERN_0013}'",
            name=op.f("ck_replay_runs_cohort_is_a_replay_cohort"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(evaluations_by_state) = 'object'",
            name=op.f("ck_replay_runs_evaluations_is_an_object"),
        ),
        sa.CheckConstraint(
            "bars_evaluated >= 0 AND signals >= 0 AND outcomes_resolved >= 0 "
            "AND outcomes_open >= 0 AND errors >= 0 AND seconds >= 0 AND decision_lag_s >= 0",
            name=op.f("ck_replay_runs_counts_are_not_negative"),
        ),
        sa.CheckConstraint(
            "cardinality(markets) > 0", name=op.f("ck_replay_runs_a_slice_visited_a_market")
        ),
        sa.CheckConstraint(
            "finished_at >= started_at", name=op.f("ck_replay_runs_finished_after_it_started")
        ),
        sa.CheckConstraint(
            "outcomes_resolved <= signals",
            name=op.f("ck_replay_runs_resolved_within_the_population"),
        ),
        sa.CheckConstraint(
            "window_to > window_from", name=op.f("ck_replay_runs_window_is_half_open")
        ),
        sa.CheckConstraint(
            "workers >= 1", name=op.f("ck_replay_runs_a_slice_had_at_least_one_worker")
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_versions.id"],
            name=op.f("fk_replay_runs_strategy_version_id_strategy_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_replay_runs")),
        sa.UniqueConstraint("run_id", "window_from", "window_to", name="uq_replay_runs_slice"),
    )
    # The scoreboard's question: this version, most recent window first. It is
    # also the index §1 requires of the foreign key — ``uq_replay_runs_slice``
    # already indexes ``run_id``, which is the other lookup.
    op.create_index(
        "ix_replay_runs_version_window",
        "replay_runs",
        ["strategy_version_id", "window_from"],
        unique=False,
    )


def _drop_table() -> None:
    op.drop_index("ix_replay_runs_version_window", table_name="replay_runs")
    op.drop_table("replay_runs")
