"""Alembic environment — async (asyncpg) against the direct, non-pooled URL.

``DATABASE_URL_MIGRATIONS`` is the connection Alembic uses: Neon's transaction
pooler cannot run DDL sessions safely, so migrations always go straight to the
primary. The URL in ``.env.example`` is written with the plain ``postgresql://``
scheme (psycopg style); it is upgraded to ``postgresql+asyncpg://`` here so one
env var serves both worlds.

``include_object`` hides partition children — both the ``candles_1m`` timeframe
level and the ``candles_1m_2026_09`` monthly leaves — from autogenerate: they are
data, created by ``infra/scripts/create_partitions.py``, not schema that belongs
in a revision. Without this, ``alembic check`` would report every partition as
drift.
"""

from __future__ import annotations

import asyncio
import re
from logging.config import fileConfig
from typing import Any, Literal, cast

from alembic import context
from sqlalchemy import pool
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from hunter_core.db.models import Base, list_partition_name, list_partitioned_tables
from hunter_core.settings import Settings

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

_PARTITION_CHILD = re.compile(r"_(?:19|20)\d{2}_(?:0[1-9]|1[0-2])$")

_LIST_PARTITIONS = frozenset(
    list_partition_name(parent, label)
    for parent, (_column, labels, _sub_key) in list_partitioned_tables().items()
    for label in labels
)
"""The intermediate ``candles_1m`` level: a partition, so also not schema drift.

Unlike the monthly leaves its name has no date to match on, and unlike the
parents it is not in the metadata — without this every one of them would be
reported by ``alembic check`` as a table the models do not declare.
"""


def _database_url() -> str:
    """The migration URL, forced onto the asyncpg driver."""
    secret = Settings().database_url_migrations
    if secret is None or not secret.get_secret_value():
        raise RuntimeError("DATABASE_URL_MIGRATIONS is not configured")
    url = secret.get_secret_value()
    if url.startswith("postgresql+"):
        return url
    return url.replace("postgresql://", "postgresql+asyncpg://", 1)


def _is_partition_child(name: str | None) -> bool:
    """True for ``candles_1m`` and for ``candles_1m_2026_09``, false for ``candles``."""
    if name is None:
        return False
    return _PARTITION_CHILD.search(name) is not None or name in _LIST_PARTITIONS


def include_object(
    obj: Any,
    name: str | None,
    type_: str,
    reflected: bool,  # positional: alembic's own hook signature
    compare_to: Any,
) -> bool:
    """Skip partition children (and anything attached to them)."""
    if type_ == "table":
        return not _is_partition_child(name)
    table = getattr(obj, "table", None)
    table_name = getattr(table, "name", None)
    if isinstance(table_name, str):
        return not _is_partition_child(table_name)
    return True


def _render_enum(enum_type: postgresql.ENUM[Any]) -> str:
    labels = ", ".join(repr(label) for label in enum_type.enums)
    return f"postgresql.ENUM({labels}, name={enum_type.name!r}, create_type=False)"


def render_item(type_: str, obj: Any, autogen_context: Any) -> str | Literal[False]:
    """Render enum columns with ``create_type=False``.

    Alembic's default rendering omits it, which makes ``op.create_table`` emit a
    ``CREATE TYPE`` per table — and a type shared by two tables then fails with
    "type already exists". ``infra/migrations/ddl/enums.py`` is the single owner
    of ``CREATE TYPE``; every autogenerated revision must defer to it.
    """
    if type_ != "type":
        return False
    if isinstance(obj, postgresql.ENUM):
        autogen_context.imports.add("from sqlalchemy.dialects import postgresql")
        return _render_enum(obj)
    if isinstance(obj, postgresql.ARRAY):
        item_type = cast("postgresql.ARRAY[Any]", obj).item_type
        if isinstance(item_type, postgresql.ENUM):
            autogen_context.imports.add("from sqlalchemy.dialects import postgresql")
            return f"postgresql.ARRAY({_render_enum(item_type)})"
    return False


def _configure(connection: Connection | None = None, url: str | None = None) -> None:
    context.configure(
        connection=connection,
        url=url,
        target_metadata=target_metadata,
        include_object=include_object,
        render_item=render_item,
        compare_type=True,
        render_as_batch=False,
        literal_binds=url is not None,
        dialect_opts={"paramstyle": "named"},
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a live connection (``alembic upgrade --sql``)."""
    _configure(url=_database_url().replace("postgresql+asyncpg://", "postgresql://", 1))
    with context.begin_transaction():
        context.run_migrations()


def _do_run_migrations(connection: Connection) -> None:
    _configure(connection=connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    """Run migrations through an async engine, driving Alembic via ``run_sync``."""
    section = config.get_section(config.config_ini_section, {})
    section["sqlalchemy.url"] = _database_url()
    engine = async_engine_from_config(section, prefix="sqlalchemy.", poolclass=pool.NullPool)
    try:
        async with engine.connect() as connection:
            await connection.run_sync(_do_run_migrations)
    finally:
        await engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
